"""One-off: replace Chinese nav labels in api-reference.html with English."""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HTML = ROOT / "api-reference.html"

PAIRS: list[tuple[str, str]] = [
    ("鏂囨。涓績", "Docs"),
    ("鏂囨。鐩綍", "Contents"),
    ("浜у搧浠嬬粛", "Product"),
    ("浜у搧姒傝堪", "Overview"),
    ("鍦烘櫙鏂规", "Use cases"),
    ("鍗曡亰/绉佷俊", "Private chat / DM"),
    ("澶氫汉缇よ亰", "Group chat"),
    ("绯荤粺閫氱煡", "System notifications"),
    ("鐩存挱鑱婂ぉ瀹?, "Live chatroom"),
    ("鏈嶅姟閮ㄧ讲", "Deployment"),
    ("鍘嗗彶鐗堟湰", "Version history"),
    ("涓€閿儴缃?, "Quick deploy"),
    ("鎵嬪姩閮ㄧ讲", "Manual deploy"),
    ("瀹㈡埛绔泦鎴?, "Client integration"),
    ("SDK 寮曞叆", "SDK setup"),
    ("蹇€熷紑濮?, "Quickstart"),
    ("浣跨敤 Vue 闆嗘垚", "Vue integration"),
    ("閫氳繃 Script 寮曞叆闆嗘垚", "Script integration"),
    ("鍙戦€佹枃浠?, "Send files"),
    ("Electorn 闆嗘垚", "Electron integration"),
    ("楦胯挋Harmony", "HarmonyOS"),
    ("SDK 鏂囨。", "SDK reference"),
    ("浼氳瘽缁撴瀯", "Conversation model"),
    ("娑堟伅缁撴瀯", "Message types"),
    ("娑堟伅瀵硅薄", "Message object"),
    ("鏂囨湰娑堟伅", "Text message"),
    ("鍚堝苟娑堟伅", "Merge message"),
    ("璇煶娑堟伅", "Voice message"),
    ("鍥剧墖娑堟伅", "Image message"),
    ("鏂囦欢娑堟伅", "File message"),
    ("瑙嗛娑堟伅", "Video message"),
    ("鍒濆鍖?, "Initialization"),
    ("鐩戝惉鐩稿叧", "Event listeners"),
    ("杩炴帴鐩戝惉", "Connection events"),
    ("浼氳瘽鐩戝惉", "Conversation events"),
    ("娑堟伅鐩戝惉", "Message events"),
    ("杩炴帴鏂规硶", "Connection API"),
    ("浼氳瘽鐩稿叧", "Conversations"),
    ("鑾峰彇浼氳瘽鍒楄〃", "Get conversation list"),
    ("鑾峰彇鍗曚釜浼氳瘽", "Get one conversation"),
    ("浼氳瘽鑽夌", "Drafts"),
    ("鑾峰彇浼氳瘽鑽夌", "Get draft"),
    ("鍒犻櫎浼氳瘽鑽夌", "Remove draft"),
    ("璁剧疆浼氳瘽鑽夌", "Set draft"),
    ("浼氳瘽鎿嶄綔", "Conversation actions"),
    ("鎻掑叆鎸囧畾浼氳瘽", "Insert conversation"),
    ("鏍囪浼氳瘽鐘舵€?, "Mark conversation state"),
    ("鍒犻櫎鎸囧畾浼氳瘽", "Remove conversation"),
    ("鑾峰彇缃《浼氳瘽", "Get pinned conversations"),
    ("璁剧疆浼氳瘽缃《", "Pin conversation"),
    ("鑾峰彇鍏ㄥ眬鍏嶆墦鎵?, "Get global DND"),
    ("璁剧疆鍏ㄥ眬鍏嶆墦鎵?, "Set global DND"),
    ("璁剧疆鍗曚釜浼氳瘽鍏嶆墦鎵?, "Set per-conversation DND"),
    ("浼氳瘽鏍囩", "Tags"),
    ("鍒涘缓鏍囩", "Create tag"),
    ("閿€姣佹爣绛?, "Destroy tag"),
    ("鏍囩浜嬩欢鐩戝惉", "Tag events"),
    ("鑾峰彇鏍囩鍒楄〃", "List tags"),
    ("鍚戞爣绛鹃噷娣诲姞浼氳瘽", "Add conversation to tag"),
    ("浠庢爣绛鹃噷鍒犻櫎浼氳瘽", "Remove conversation from tag"),
    ("鑾峰彇鏍囩浼氳瘽鍒楄〃", "Conversations in tag"),
    ("鏈鏁?, "Unread counts"),
    ("鑾峰彇浼氳瘽鏈鎬绘暟", "Total unread count"),
    ("娓呯┖浼氳瘽鏈鎬绘暟", "Clear total unread"),
    ("娓呯┖鍗曚釜浼氳瘽鏈鏁?, "Clear unread for conversation"),
    ("娑堟伅鐩稿叧", "Messages"),
    ("娑堟伅鍙戦€?, "Sending"),
    ("鍙戦€佹秷鎭?, "Send message"),
    ("鍙戦€佸浘鐗?, "Send image"),
    ("鍙戦€佽棰?, "Send video"),
    ("鍙戦€佽闊?, "Send voice"),
    ("鑾峰彇鍘嗗彶娑堟伅", "Get message history"),
    ("缇ゅ彂鍔╂墜", "Broadcast helper"),
    ("鍚堝苟杞彂", "Combined forward"),
    ("鍙戦€佽嚜瀹氫箟娑堟伅", "Custom message"),
    ("鍘嗗彶娑堟伅", "History"),
    ("鑾峰彇 @ 娑堟伅", "Get @ mentions"),
    ("娓呯┖鍘嗗彶娑堟伅", "Clear history"),
    ("鍒犻櫎鍘嗗彶娑堟伅", "Delete history"),
    ("鑾峰彇娑堟伅涓婁笅鏂?, "Message context"),
    ("閫氳繃 Id 鑾峰彇鍘嗗彶娑堟伅", "Get history by IDs"),
    ("娑堟伅鎿嶄綔", "Message actions"),
    ("淇敼娑堟伅", "Update message"),
    ("璁剧疆宸茶", "Mark as read"),
    ("鎾ゅ洖娑堟伅", "Recall message"),
    ("鏈湴娑堟伅鎼滅储", "Local search"),
    ("淇敼鏈湴娑堟伅鎵╁睍", "Update local extras"),
    ("娑堟伅鍥炲簲", "Reactions"),
    ("鍥炲簲浜嬩欢鐩戝惉", "Reaction events"),
    ("娣诲姞娑堟伅鍥炲簲", "Add reaction"),
    ("鍒犻櫎娑堟伅鍥炲簲", "Remove reaction"),
    ("娑堟伅缃《", "Pinned messages"),
    ("缃《鐩戝惉", "Pin events"),
    ("璁剧疆缃《", "Pin message"),
    ("鏌ヨ缃《", "Query pinned"),
    ("娑堟伅鏀惰棌", "Favorites"),
    ("娣诲姞鏀惰棌", "Add favorite"),
    ("绉婚櫎鏀惰棌", "Remove favorite"),
    ("鏌ヨ鏀惰棌", "Query favorites"),
    ("娑堟伅璁㈤槄", "Subscriptions"),
    ("鑱婂ぉ瀹ょ浉鍏?, "Chatroom"),
    ("鑱婂ぉ瀹ょ洃鍚?, "Chatroom events"),
    ("鍔犲叆鑱婂ぉ瀹?, "Join chatroom"),
    ("鍔犲叆骞跺垱寤鸿亰澶╁", "Join or create"),
    ("閫€鍑鸿亰澶╁", "Leave chatroom"),
    ("璁剧疆灞炴€?, "Set attributes"),
    ("鍒犻櫎灞炴€?, "Remove attributes"),
    ("鑾峰彇鍏ㄩ儴灞炴€?, "Get all attributes"),
    ("鑾峰彇鎸囧畾灞炴€?, "Get attributes"),
    ("鍙戦€佽亰澶╁娑堟伅", "Send chatroom message"),
    ("鏋氫妇鐩稿叧", "Enumerations"),
    ("鐘舵€佺爜", "Status codes"),
    ("闊宠棰戦€氳瘽", "Voice & video calls"),
    ("閫氳瘽瀹炰綋", "Call session"),
    ("鏉ョ數鐩戝惉", "Incoming call"),
    ("鍙戣捣閫氳瘽", "Start call"),
    ("浜嬩欢鐩戝惉", "Call events"),
    ("閫氳瘽缁撴潫娑堟伅", "Call end message"),
    ("鏃ュ織鐩稿叧", "Logging"),
    ("鎺ㄩ€侀泦鎴?, "Push"),
    ("Android 闆嗘垚", "Android push"),
    ("iOS 鏅€氭帹閫?, "iOS push"),
    ("iOS VoIP 鎺ㄩ€?, "iOS VoIP"),
    ("鐢ㄦ埛淇℃伅", "User info"),
    ("鎺ュ彛璇存槑", "API overview"),
    ("娉ㄥ唽鐧诲綍", "Authentication"),
    ("璐﹀彿娉ㄥ唽", "Register"),
    ("鐭俊楠岃瘉鐮?, "SMS code"),
    ("鐭獙鐧诲綍", "SMS login"),
    ("閭楠岃瘉鐮?, "Email code"),
    ("閭鐧诲綍", "Email login"),
    ("鐧诲綍浜岀淮鐮?, "Login QR"),
    ("妫€鏌ユ壂鐮佺姸鎬?, "Check QR status"),
    ("鎵爜纭", "Confirm QR scan"),
    ("鐢ㄦ埛鐩稿叧", "Users"),
    ("鑾峰彇鐢ㄦ埛淇℃伅", "Get user"),
    ("鏇存柊鐢ㄦ埛淇℃伅", "Update user"),
    ("鏇存柊鐢ㄦ埛璁剧疆", "Update settings"),
    ("鎼滅储鐢ㄦ埛", "Search users"),
    ("鐢ㄦ埛榛戝悕鍗?, "Blocklist"),
    ("娣诲姞鐢ㄦ埛榛戝悕鍗?, "Add to blocklist"),
    ("绉婚櫎鐢ㄦ埛榛戝悕鍗?, "Remove from blocklist"),
    ("鏌ヨ榛戝悕鍗曠敤鎴峰垪琛?, "List blocked users"),
    ("濂藉弸鐩稿叧", "Friends"),
    ("鐢宠娣诲姞濂藉弸", "Request friend"),
    ("澶勭悊濂藉弸鐢宠", "Handle request"),
    ("濂藉弸鐢宠鍒楄〃", "Friend requests"),
    ("绉婚櫎濂藉弸", "Remove friend"),
    ("濂藉弸鍒楄〃", "Friend list"),
    ("濂藉弸鎼滅储", "Search friends"),
    ("缇ょ粍鐩稿叧", "Groups"),
    ("缇ょ粍绠＄悊", "Management"),
    ("鍒涘缓缇ょ粍", "Create group"),
    ("鏇存柊缇ょ粍淇℃伅", "Update group"),
    ("瑙ｆ暎缇ょ粍", "Dissolve group"),
    ("鏌ヨ缇や俊鎭?, "Get group info"),
    ("鏌ヨ鍔犲叆鐨勭兢鍒楄〃", "My groups"),
    ("鎼滅储鍔犲叆鐨勭兢", "Search my groups"),
    ("缇ょ粍璁剧疆", "Settings"),
    ("鍙樻洿缇や富", "Transfer owner"),
    ("璁剧疆缇ょ瑷€", "Mute group"),
    ("璁剧疆鍏ョ兢楠岃瘉绫诲瀷", "Join verification"),
    ("鏂颁汉鍏ョ兢鏄惁鍙煡鐪嬪巻鍙叉秷鎭?, "New member history visibility"),
    ("璁剧疆缇ゅ叕鍛?, "Set announcement"),
    ("鏌ヨ缇ゅ叕鍛?, "Get announcement"),
    ("璁剧疆缇ゆ樀绉?, "Set group nickname"),
    ("璁剧疆缇ゆ垚鍛樼瑷€", "Mute members"),
    ("鎴愬憳绠＄悊", "Members"),
    ("閭€璇峰叆缇?, "Invite"),
    ("閫€鍑虹兢缁?, "Leave group"),
    ("绉婚櫎缇ゆ垚鍛?, "Remove member"),
    ("鏌ヨ缇ゆ垚鍛樺垪琛?, "List members"),
    ("鐢宠鍏ョ兢", "Request to join"),
    ("鎼滅储缇ゆ垚鍛?, "Search members"),
    ("妫€鏌ユ槸鍚︾兢鎴愬憳", "Check membership"),
    ("缇ょ鐞嗗憳", "Admins"),
    ("娣诲姞绠＄悊鍛?, "Add admin"),
    ("绉婚櫎绠＄悊鍛?, "Remove admin"),
    ("鏌ヨ缇ょ鐞嗗憳鍒楄〃", "List admins"),
    ("Bot鐩稿叧", "Bots"),
    ("Bot鍒楄〃", "Bot list"),
    ("AI鍔╃悊鐩稿叧", "AI assistants"),
    ("鏂板鎻愮ず璇?, "Add prompt"),
    ("鏇存柊鎻愮ず璇?, "Update prompt"),
    ("鍒犻櫎鎻愮ず璇?, "Delete prompt"),
    ("鎵归噺鍒犻櫎鎻愮ず璇?, "Batch delete prompts"),
    ("鏌ヨ鎻愮ず璇?, "List prompts"),
    ("鏅鸿兘鍥炲", "AI reply"),
    ("Telegram Bot鐩稿叧", "Telegram bots"),
    ("娣诲姞Bot", "Add bot"),
    ("绉婚櫎Bot", "Remove bot"),
    ("鏈嬪弸鍦堢浉鍏?, "Posts"),
    ("鍙戝竷甯栧瓙", "Create post"),
    ("甯栧瓙鍒楄〃", "Post list"),
    ("鍙戝竷璇勮", "Add comment"),
    ("璇勮鍒楄〃", "Comments"),
    ("缈昏瘧鐩稿叧", "Translation"),
    ("缈昏瘧", "Translate"),
    ("鏂囦欢鐩稿叧", "Files"),
    ("涓婁紶token", "Upload token"),
    ("淇℃伅鍙嶉", "Feedback"),
    ("涓婃姤鍙嶉", "Submit feedback"),
    ("宸ヤ綔鍙?, "Workspace"),
    ("搴旂敤鍒楄〃", "Applications"),
    ("绠＄悊鍛樻挙鍥炴秷鎭?, "Admin recall"),
    ("绠＄悊鍛樺垹闄ゆ秷鎭?, "Admin delete"),
    ("鏈嶅姟绔泦鎴?, "Server integration"),
    ("绂佸彂绉佽亰娑堟伅", "Private send restrictions"),
    ("娣诲姞绂佸彂鍗曡亰娑堟伅鐢ㄦ埛", "Add private-send banned user"),
    ("鍒犻櫎绂佸彂鍗曡亰娑堟伅鐢ㄦ埛", "Remove private-send banned user"),
    ("鏌ヨ绂佸彂鍗曡亰娑堟伅鐢ㄦ埛", "Query private-send banned users"),
    ("娉ㄥ唽鐢ㄦ埛", "Register user"),
    ("灏佺鐢ㄦ埛", "Ban user"),
    ("瑙ｇ鐢ㄦ埛", "Unban user"),
    ("鏌ヨ灏佺鍒楄〃", "Banned user list"),
    ("鏌ヨ鍦ㄧ嚎鐘舵€?, "Online status"),
    ("璁剧疆鍗曡亰绂佽█", "Private chat mute"),
    ("瑙ｉ櫎鍗曡亰绂佽█", "Remove private mute"),
    ("鍗曡亰绂佽█鍒楄〃", "Private mute list"),
    ("韪㈢敤鎴蜂笅绾?, "Kick user"),
    ("鍙戦€佸崟鑱婃秷鎭?, "Send private message"),
    ("娴佸紡娑堟伅", "Streaming"),
    ("鍒涘缓娴佸紡娑堟伅", "Create stream message"),
    ("鍙戦€佺兢鑱婃秷鎭?, "Send group message"),
    ("鍙戦€佺郴缁熸秷鎭?, "Send system message"),
    ("鍙戦€佺兢鍙戞秷鎭?, "Send mass message"),
    ("鍙戦€佸箍鎾秷鎭?, "Send broadcast"),
    ("鍙戦€佽亰澶╁骞挎挱娑堟伅", "Send chatroom broadcast"),
    ("鏍囪娑堟伅宸茶", "Mark messages read"),
    ("鏇存柊缇や俊鎭?, "Update group info"),
    ("娣诲姞缇ゆ垚鍛?, "Add members"),
    ("璁剧疆缇ゆ垚鍛樼櫧鍚嶅崟", "Member allowlist"),
    ("鎸夋垚鍛?ID 鏌ヨ淇℃伅", "Get members by IDs"),
    ("璁剧疆缇ゆ垚鍛樺睘鎬?, "Set member attributes"),
    ("璁剧疆鍏嶆墦鎵?, "Set DND"),
    ("鍒犻櫎浼氳瘽", "Delete conversation"),
    ("娣诲姞浼氳瘽", "Add conversation"),
    ("鏌ヨ鍏ㄥ眬浼氳瘽鍒楄〃", "Global conversation list"),
    ("娓呯悊鏈鏁?, "Clear unread"),
    ("璁剧疆缃《鐘舵€?, "Set pinned state"),
    ("鍒犻櫎娑堟伅", "Delete message"),
    ("娑堟伅鎾ゅ洖", "Recall message"),
    ("娑堟伅淇敼", "Modify message"),
    ("瀵煎叆鍘嗗彶娑堟伅", "Import history"),
    ("涓婁笅绾胯闃?, "Presence subscription"),
    ("鑱婂ぉ娑堟伅璁㈤槄", "Message subscription"),
    ("娑堟伅鍥炶皟", "Message callback"),
    ("鏁忔劅璇嶇浉鍏?, "Sensitive words"),
    ("娣诲姞鏁忔劅璇?, "Add word"),
    ("鍒犻櫎鏁忔劅璇?, "Delete word"),
    ("鏌ヨ鏁忔劅璇?, "Query words"),
    ("鏍囩鎺ㄩ€?, "Tagged push"),
    ("娣诲姞鐢ㄦ埛鏍囩", "Add user tags"),
    ("鍒犻櫎鐢ㄦ埛鏍囩", "Delete user tags"),
    ("娓呯┖鐢ㄦ埛鏍囩", "Clear user tags"),
    ("娓呴櫎鐢ㄦ埛鏍囩", "Remove user tags"),
    ("鍏ㄥ憳/鏍囩鎺ㄩ€?, "Broadcast / tag push"),
    ("鍒涘缓鑱婂ぉ瀹?, "Create chatroom"),
    ("閿€姣佽亰澶╁", "Destroy chatroom"),
    ("鏌ヨ鑱婂ぉ瀹や俊鎭?, "Get chatroom info"),
    ("鑱婂ぉ瀹ゅ睘鎬?, "Chatroom attributes"),
    ("璁剧疆鑱婂ぉ瀹ゅ睘鎬?, "Set chatroom attribute"),
    ("鍒犻櫎鑱婂ぉ瀹ゅ睘鎬?, "Remove chatroom attribute"),
    ("鏌ヨ鑱婂ぉ瀹ゆ寚瀹氬睘鎬?, "Get chatroom attribute"),
    ("鏌ヨ鑱婂ぉ瀹ゅ叏閲忓睘鎬?, "List all attributes"),
    ("鑱婂ぉ瀹ょ瑷€", "Chatroom mute"),
    ("璁剧疆鑱婂ぉ瀹ゅ叏灞€绂佽█", "Global chatroom mute"),
    ("鑱婂ぉ瀹ゆ垚鍛樼瑷€", "Member mute"),
    ("娣诲姞鑱婂ぉ瀹ゆ垚鍛樼瑷€", "Mute chatroom member"),
    ("绉婚櫎鑱婂ぉ瀹ゆ垚鍛樼瑷€", "Unmute chatroom member"),
    ("鏌ヨ绂佽█鐨勮亰澶╁鎴愬憳", "List muted members"),
    ("鑱婂ぉ瀹ゅ皝绂?, "Chatroom ban"),
    ("娣诲姞鑱婂ぉ瀹ゆ垚鍛樺皝绂?, "Ban chatroom member"),
    ("绉婚櫎鑱婂ぉ瀹ゆ垚鍛樺皝绂?, "Unban chatroom member"),
    ("鏌ヨ灏佺鐨勮亰澶╁鎴愬憳", "List banned members"),
    ("鑱婂ぉ瀹ょ櫧鍚嶅崟", "Chatroom allowlist"),
    ("娣诲姞鑱婂ぉ瀹ゆ垚鍛樼櫧鍚嶅崟", "Add allowlist member"),
    ("绉婚櫎鑱婂ぉ瀹ゆ垚鍛樼櫧鍚嶅崟", "Remove allowlist member"),
    ("鏌ヨ鑱婂ぉ瀹ゆ垚鍛樼櫧鍚嶅崟", "List allowlist"),
    ("娣诲姞濂藉弸", "Add friend"),
    ("鍒犻櫎濂藉弸", "Delete friend"),
    ("鏌ヨ濂藉弸鍒楄〃", "Friend list"),
    ("璁剧疆濂藉弸澶囨敞鍚?, "Set friend alias"),
    ("鏇存柊缇よ缃?, "Update group settings"),
    ("鏌ヨ缇ゆ垚鍛?, "Query members"),
    ("娣诲姞濂藉弸澶囨敞", "Set friend note"),
    ("璁剧疆缇ら厤缃?, "Set group config"),
    ("瀹℃壒閭€璇峰叆缇ょ敵璇?, "Approve join invites"),
    ("鍏ョ兢鐢宠鍒楄〃", "Join requests"),
    ("鍒犻櫎甯栧瓙", "Delete post"),
    ("甯栧瓙淇℃伅", "Post info"),
    ("鏇存柊甯栧瓙", "Update post"),
    ("娣诲姞鐐硅禐", "Add like"),
    ("绉婚櫎鐐硅禐", "Remove like"),
    ("鐐硅禐鍒楄〃", "Likes list"),
    ("缁戝畾閭", "Bind email"),
    ("缁戝畾閭-鍙戦€侀偖浠?, "Bind email 鈥?send mail"),
    ("缁戝畾鎵嬫満鍙?, "Bind phone"),
    ("缁戝畾鎵嬫満鍙?鍙戦€佺煭淇?, "Bind phone 鈥?send SMS"),
    ("鏇存柊瀵嗙爜", "Update password"),
    ("鍙戝竷鏈嬪弸鍦?, "Publish moment"),
    ("鍒犻櫎鏈嬪弸鍦?, "Delete moment"),
    ("鏈嬪弸鍦堜俊鎭?, "Moment info"),
    ("鏈嬪弸鍦堝垪琛?, "Moment feed"),
    ("鏇存柊鏈嬪弸鍦?, "Update moment"),
    ("鑷畾涔夋秷鎭笂浼?, "Custom message upload"),
    ("鑾峰彇绗竴鏉℃湭璇绘秷鎭?, "First unread message"),
    ("鑾峰彇娑堟伅鍥炲簲", "Get reactions"),
    ("娣诲姞璇勮", "Add comment"),
    ("鍒犻櫎璇勮", "Delete comment"),
    ("鏁版嵁缁撴瀯", "Data structures"),
    ("娣诲姞鏈嬪弸鍦?, "Add moment"),
    ("鑾峰彇鏈嬪弸鍦?, "Get moment"),
    ("鍒犻櫎鐐硅禐", "Remove like"),
    ("閮ㄧ讲妯″紡", "Deployment modes"),
    ("鍒涘缓鍏紬鍙?, "Create channel"),
    ("閿€姣佸叕浼楀彿", "Delete channel"),
    ("鍏紬鍙疯闃呭垪琛?, "Channel subscribers"),
    ("璁㈤槄鍏紬鍙?, "Subscribe"),
    ("鍙栨秷璁㈤槄鍏紬鍙?, "Unsubscribe"),
    ("鏇存柊鍏紬鍙?, "Update channel"),
    ("鍙戦€佸叕浼楀彿娑堟伅", "Send channel message"),
    ("娣诲姞绂佸彂缇よ亰娑堟伅鐢ㄦ埛", "Add group-send banned user"),
    ("鍒犻櫎绂佸彂缇よ亰娑堟伅鐢ㄦ埛", "Remove group-send banned user"),
    ("鏌ヨ绂佸彂缇よ亰娑堟伅鐢ㄦ埛", "Query group-send banned users"),
    ("璁剧疆浼氳瘽鏍囩", "Set conversation tags"),
    ("绉婚櫎浼氳瘽鏍囩", "Remove conversation tags"),
    ("鑾峰彇鏍囩鏈娑堟伅鏁?, "Tag unread count"),
    ("鑷姩閿€姣?, "Auto destroy"),
    ("闃呭悗鍗崇剼", "Burn after read"),
    ("缇ょ粍淇℃伅", "Group info"),
    ("缇ょ粍鎴愬憳淇℃伅", "Group member info"),
    ("鐧诲綍", "Login"),
    ("鍙戦€佹祦寮忔秷鎭?, "Send stream message"),
    ("鏇存柊璇勮", "Update comment"),
    ("鏌ヨ鐢ㄦ埛淇℃伅", "Query user"),
    ("鏌ヨ鍘嗗彶娑堟伅", "Query history"),
    ("娓呯┖鍘嗗彶娑堟伅", "Clear history"),
    ("璐︽埛瀵嗙爜鐧诲綍", "Password login"),
]


def main() -> None:
    text = HTML.read_text(encoding="utf-8")
    text = text.replace('lang="zh-CN"', 'lang="en"', 1)
    for zh, en in sorted(PAIRS, key=lambda x: -len(x[0])):
        text = text.replace(zh, en)
    # Repair if shorter keys broke longer phrases (e.g. 鍘嗗彶娑堟伅 before 鑾峰彇鍘嗗彶娑堟伅)
    text = text.replace("鑾峰彇History", "Get message history")
    HTML.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()

